name: Publish to Webstore
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Deploy and Release extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn run build-zip
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@2.0.0
        with:
          file-path: build.zip
          extension-id: hogefuga(pjffalefhahlellpckbbiehmbljjhihl)
          client-id: ${{ secrets.CLIENT_ID }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          glob: true
